### ISSUE TITLE
Quark Oddities incompability

### ISSUE THREAD

**Issue by Tortyash** [gloridifice/WaterSource#16]
Mods used
1.16.5-forge-36.1.32
AutoRegLib-1.6-49
Quark-r2.4-313
QuarkOddities-1.16.3
WaterSoucre-1.1.19-alpha-1.16.5

[crash-2021-06-26_08.18.50-server.txt](https://github.com/lemon-slice-studio/WaterSource/files/6719621/crash-2021-06-26_08.18.50-server.txt)

**Comment by gloridifice** [comment]
Thank you, I found the reason. It will be fixed in next version.
