### ISSUE TITLE
Recipe Serializer Error

### ISSUE THREAD

**Issue by WenXin20** [gloridifice/WaterSource#19]
`Minecraft v1.16.5`
`Forge v36.1.24`
`Water Source v1.1.22`

While investigating why recipes were not displaying in jei, I discovered that Water Source was the cause for that because of this error in the logs: `java.io.UTFDataFormatException: malformed input around byte 65`
[Latest.log](https://gist.github.com/WenXin20/4541696d7b282d6a22843bb975d8661b#file-latest-log-L6483)

**Comment by gloridifice** [comment]
Sorry, I didn't reproduce this bug successfully. Was all recipes disappear in jei, or just part of it?

**Comment by WenXin20** [comment]
It was all crafting bench recipes and on my server. Did you see the error on line 6483 of the latest.log?
