### ISSUE TITLE
Error in WaterFilterStrainerHUD

### ISSUE THREAD

**Issue by Doc94** [gloridifice/WaterSource#35]
Hi in last version i get a crash with a error in HUD.

Crash log: https://gist.github.com/Doc94/33f40b8a1e6c8f0d82f698d2b5c50157

**Comment by gloridifice** [comment]
Thank you! I try fixing it in 1.1.31 version. Can you have a testing?

**Comment by Doc94** [comment]
In previous to the last version i has a crash because a creeper explode the container and set only one block then when click crash.. not sure if is the same issue.. but not has logs.
