### ISSUE TITLE
"purified_water" do not have fluid feature

### ISSUE THREAD

**Issue by Sam-Chai** [gloridifice/WaterSource#38]
purified water don't have any "fluidy" feature in minecraft.
such as this:

![image](https://user-images.githubusercontent.com/29940426/134672100-fc3b2385-c850-49d7-b200-8bfd821eddef.png)

The left one is normal water fluid, the "Watery Block" looks normally
The right one is purified water, No watery block feature 
Players can’t swim or something like normal water in purified water.

Also, in create and tconstruct ‘s fluid container (can see what the fluid is), the purified water no any texture in it.

![image](https://user-images.githubusercontent.com/29940426/134672825-d189f6f9-58b7-4328-b2ff-4108a9d5d773.png)
![image](https://user-images.githubusercontent.com/29940426/134673185-52a4a119-dc4f-4b57-b711-41b4effe7bb3.png)

This two container have some purified water in it, but cannot see it.

This mod is fantastic, but there is a tiny problem. hope to fix it. 👏

**Comment by Sam-Chai** [comment]
I tested just now, the "soul_water" also have this problem

**Comment by gloridifice** [comment]
Thank you, I will fix it.
