### ISSUE TITLE
Palm Tress Snowy Beach

### ISSUE THREAD

**Issue by Jollyolsport** [gloridifice/WaterSource#41]
![2021-09-29_23 37 53](https://user-images.githubusercontent.com/64448764/135383169-8c685ae3-b16e-4108-91a4-736df7e12a5d.png)

Palm trees spawn in snowy beach biomes; they seem out of place given they are tropical plants

**Comment by gloridifice** [comment]
Thank you, this condition won't appear in 1.1.35.
