### ISSUE TITLE
Bug when try to take water

### ISSUE THREAD

**Issue by Doc94** [gloridifice/WaterSource#43]
Hi, i currently using this modpack https://www.curseforge.com/minecraft/modpacks/nefastoland/
and when drink water in many cases the animation show but not drink, in other cases drink correctly but most cases the drink animation take so long.

**Comment by Drakoflame** [comment]
I'm having the same issue with not being able to drink properly, or my thirst will randomly fill, or drop down super quick, I suspect that Apple Skin might be caushing some issues, as that's a mod that does stuff with the hud. The only other mods that I have in common with that pack are:
Curios
Immersive Engineering
Immersive Petrolium
Patchouli
Serene Seasons
Waystones

I'm going to do some testing really quick and see if the but still occurs with Apple Skin

**Comment by Drakoflame** [comment]
Alright, did my testing, it's still broken. I ran into the issue where I hold right click with the water bag and just wasted all the water and go no thirst
