### ISSUE TITLE
与夸克模组的的兼容性问题和一些小建议

### ISSUE THREAD

**Issue by Keletu** [gloridifice/WaterSource#5]
![2020-07-23_20 10 29](https://user-images.githubusercontent.com/64598399/88285050-09305a00-cd21-11ea-8b81-cce481781ca8.png)
如图，补水量显示与夸克药水效果提示有冲突，希望能修复
还有一些小建议：
1.我不是很希望mcbbs上面有人提出的"真实硬核"喝水机制（喝生水会给一堆debuff而不是一种）被全盘接受并实装到游戏中，因为那很不mc，喝水会给一堆debuff看似没错，实则与原版吃生肉甚至吃腐肉最多给饥饿debuff的差别很大，影响体验。
2.虽然我不是很赞成他的意见，但如果您已经计划要把模组净水变得更加真实，可以进行如下改动：
（1）.生水分为脏水和海水，分别继承原版蜘蛛眼和腐肉的debuff与腐肉与蜘蛛眼的回口渴值（原版为饱食度）回复量，脏水喝完80%的几率会得到中毒I时长4s，回4点口渴值；海水喝完必定会得到时长30s的口渴Idebuff，回2点口渴值
（2）.在海洋生物群系用空瓶接水为海水，此外为脏水
3.吃一些烤制肉食会直接降低口渴值，例如吃一块牛排降低2点口渴值，烤鸡肉降低1点
4.饥饿值已满口渴值不满可以吃补水食物，溢出的饱食度可以累积到饱和度上
5.与夸克模组的联动（为一些食物加口渴值回复）
希望以上建议可以被接受或者部分被采纳，提前感谢~

**Comment by Keletu** [comment]
![2020-07-23_20 10 29](https://user-images.githubusercontent.com/64598399/88287169-86a99980-cd24-11ea-919a-8967929bb703.png)

**Comment by gloridifice** [comment]
谢谢反馈！冲突会尽快修复，建议会部分采纳
