### ISSUE TITLE
Missing block tags

### ISSUE THREAD

**Issue by hammertater** [gloridifice/WaterSource#50]
Coconut leaves should have the `minecraft:leaves` tag. The missing tag is causing weird behavior with other mods (https://github.com/hammertater/treechop/issues/85)

Also, it would probably be better to put the coconut log blocks under `minecraft:logs_that_burn` - right now they're only in `minecraft:logs`, which pools `logs_that_burn` with mushrooms and such.

**Comment by gloridifice** [comment]
Thank you ! They will be updated in 1.1.35
