### ISSUE TITLE
[1.18] Broken interactions in new version release

### ISSUE THREAD

**Issue by ffuentesm** [gloridifice/WaterSource#55]
I can't right-click on the water filters to add water using a bucket or to add paper filters.
But I can add water if I use a pipe into it. 
Iron bottle is consumed when I drink the last water. 
Iron bottle turns into a wooden cup if I refill it in a stone rain collector, while the iron bottle still have some water in it.

**Comment by gloridifice** [comment]
Thank you, it's fixed in 1.3.46.
