### ISSUE TITLE
Data Tag Mispell

### ISSUE THREAD

**Issue by ghost** [gloridifice/WaterSource#6]
on  WaterSource/src/main/resources/data/minecraft/tags/blocks/buttons.json and  WaterSource/src/main/resources/data/minecraft/tags/items/buttons.json 

the value "watersource:coconut_tree_buttons" should be "watersource:coconut_tree_button".

Loading any world fires up an error on the console (MultiMC), but it doesn't seem to affect gameplay much (the world loads normally).

**Comment by gloridifice** [comment]
Thank you.
