### ISSUE TITLE
JEICompat Error

### ISSUE THREAD

**Issue by ghost** [gloridifice/WaterSource#8]
loading WaterSource-1.0.16b1-beta-1.15.2 with JEI fires this error:

[Render thread/ERROR] [me.je.lo.PluginCaller/]: Caught an error from mod plugin: class gloridifice.watersource.plugin.jei.JEICompat watersource:recipe
java.lang.IllegalArgumentException: recipeCategories must not be empty.

this doesn't happen with the old version.

**Comment by gloridifice** [comment]
Thank you.It will be fixed in next version.
